[package]
name = "lists"
version = "0.1.0"
authors = ["Takanori Ishibashi <takanori.1112@gmail.com>"]

[dependencies]
csv = "0.14.7"
rustc-serialize = "0.3.22"
hyper = "~0.7"


[dependencies.url]
git = "https://github.com/servo/rust-url"